"""Dashboard service -- serves the FastAPI app via uvicorn."""

from __future__ import annotations

import asyncio
import contextlib
import logging
import socket
from typing import Any

import uvicorn

from rex.shared.constants import (
    STREAM_BRAIN_DECISIONS,
    STREAM_CORE_HEALTH,
    STREAM_EYES_DEVICE_UPDATES,
    STREAM_EYES_SCAN_RESULTS,
    STREAM_EYES_THREATS,
)
from rex.shared.enums import ServiceName
from rex.shared.service import BaseService

logger = logging.getLogger(__name__)


def _port_is_available(host: str, port: int) -> bool:
    """Return True if *port* on *host* is free to bind."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        try:
            sock.bind((host, port))
            return True
        except OSError:
            return False


class DashboardService(BaseService):
    """Serves the REX dashboard API and static frontend via uvicorn."""

    @property
    def service_name(self) -> ServiceName:
        return ServiceName.DASHBOARD

    async def _on_start(self) -> None:
        """Start uvicorn in a background task."""
        from rex.dashboard.app import create_app

        host = self.config.dashboard_host
        port = self.config.dashboard_port

        # Fail fast if port is already in use
        if not _port_is_available(host, port):
            raise OSError(
                f"Port {port} is already in use on {host}. "
                f"Kill the existing process (sudo fuser -k {port}/tcp) "
                f"or set REX_DASHBOARD_PORT to a different port."
            )

        app = create_app()

        # Enable TLS if certificates exist (generated by install.sh)
        ssl_kwargs: dict[str, str] = {}
        cert_file = self.config.certs_dir / "cert.pem"
        key_file = self.config.certs_dir / "key.pem"
        if cert_file.exists() and key_file.exists():
            ssl_kwargs["ssl_certfile"] = str(cert_file)
            ssl_kwargs["ssl_keyfile"] = str(key_file)
            logger.info("TLS enabled with certs from %s", self.config.certs_dir)
        else:
            logger.warning(
                "No TLS certs found at %s -- running without HTTPS. "
                "Generate certs with install.sh or provide cert.pem/key.pem.",
                self.config.certs_dir,
            )

        config = uvicorn.Config(
            app,
            host=host,
            port=port,
            log_level=self.config.log_level,
            access_log=False,
            **ssl_kwargs,
        )
        self._server = uvicorn.Server(config)
        self._serve_task = asyncio.create_task(self._server.serve())
        self._tasks.append(self._serve_task)
        scheme = "https" if ssl_kwargs else "http"
        logger.info(
            "Dashboard serving on %s://%s:%d",
            scheme, host, port,
        )

    async def _on_stop(self) -> None:
        """Shutdown uvicorn completely, ensuring port is released."""
        if not hasattr(self, "_server"):
            logger.info("Dashboard stopped (no server)")
            return

        # Step 1: signal graceful exit
        self._server.should_exit = True

        # Step 2: wait for serve task with timeout
        if hasattr(self, "_serve_task") and not self._serve_task.done():
            try:
                await asyncio.wait_for(self._serve_task, timeout=5)
            except (TimeoutError, asyncio.TimeoutError):  # noqa: UP041 (Py3.10 runtime)
                # Step 3: force exit if graceful didn't work
                logger.warning("Dashboard graceful shutdown timed out, forcing exit")
                self._server.force_exit = True
                self._serve_task.cancel()
                with contextlib.suppress(asyncio.CancelledError, OSError):
                    await self._serve_task
            except (asyncio.CancelledError, OSError, RuntimeError):
                # RuntimeError can occur during interpreter teardown/event-loop close.
                logger.debug("Dashboard serve task ended during loop teardown", exc_info=True)
                pass

        logger.info("Dashboard stopped")

    async def _consume_loop(self) -> None:
        """Subscribe to key event streams and forward to WebSocket clients."""
        from rex.dashboard.app import _ws_manager

        # Map internal event types to canonical WS channel names.
        # The WebSocket manager and frontend both use the dotted names on the right.
        event_to_channel = {
            "threat_detected": "threat.new",
            "threat_resolved": "threat.resolved",
            "device_discovered": "device.new",
            "new_device": "device.new",
            "device_departed": "device.departed",
            "device_update": "device.update",
            "scan_complete": "scan.complete",
            "status_change": "status.update",
        }

        async def handler(event: Any) -> None:
            raw_type = event.event_type
            channel = event_to_channel.get(raw_type, raw_type.replace("_", "."))
            timestamp = (
                event.timestamp.isoformat()
                if hasattr(event.timestamp, "isoformat")
                else str(event.timestamp)
            )
            await _ws_manager.broadcast(
                {"payload": event.payload, "timestamp": timestamp},
                channel=channel,
            )

        await self.bus.subscribe(
            [
                STREAM_EYES_THREATS,
                STREAM_EYES_DEVICE_UPDATES,
                STREAM_EYES_SCAN_RESULTS,
                STREAM_BRAIN_DECISIONS,
                STREAM_CORE_HEALTH,
            ],
            handler,
        )
