"""Dashboard service -- serves the FastAPI app via uvicorn."""

from __future__ import annotations

import asyncio
import logging
from typing import Any

import uvicorn

from rex.shared.constants import (
    STREAM_BRAIN_DECISIONS,
    STREAM_CORE_HEALTH,
    STREAM_EYES_DEVICE_UPDATES,
    STREAM_EYES_SCAN_RESULTS,
    STREAM_EYES_THREATS,
)
from rex.shared.enums import ServiceName
from rex.shared.service import BaseService

logger = logging.getLogger(__name__)


class DashboardService(BaseService):
    """Serves the REX dashboard API and static frontend via uvicorn."""

    @property
    def service_name(self) -> ServiceName:
        return ServiceName.DASHBOARD

    async def _on_start(self) -> None:
        """Start uvicorn in a background task."""
        from rex.dashboard.app import create_app

        app = create_app()

        # Enable TLS if certificates exist (generated by install.sh)
        ssl_kwargs: dict[str, str] = {}
        cert_file = self.config.certs_dir / "cert.pem"
        key_file = self.config.certs_dir / "key.pem"
        if cert_file.exists() and key_file.exists():
            ssl_kwargs["ssl_certfile"] = str(cert_file)
            ssl_kwargs["ssl_keyfile"] = str(key_file)
            logger.info("TLS enabled with certs from %s", self.config.certs_dir)
        else:
            logger.warning(
                "No TLS certs found at %s -- running without HTTPS. "
                "Generate certs with install.sh or provide cert.pem/key.pem.",
                self.config.certs_dir,
            )

        config = uvicorn.Config(
            app,
            host=self.config.dashboard_host,
            port=self.config.dashboard_port,
            log_level=self.config.log_level,
            access_log=False,
            **ssl_kwargs,
        )
        self._server = uvicorn.Server(config)
        self._serve_task = asyncio.create_task(self._server.serve())
        self._tasks.append(self._serve_task)
        scheme = "https" if ssl_kwargs else "http"
        logger.info(
            "Dashboard serving on %s://%s:%d",
            scheme,
            self.config.dashboard_host,
            self.config.dashboard_port,
        )

    async def _on_stop(self) -> None:
        """Shutdown uvicorn."""
        if hasattr(self, "_server"):
            self._server.should_exit = True
        logger.info("Dashboard stopped")

    async def _consume_loop(self) -> None:
        """Subscribe to key event streams and forward to WebSocket clients."""
        from rex.dashboard.app import _ws_manager

        # Map internal event types to canonical WS channel names.
        # The WebSocket manager and frontend both use the dotted names on the right.
        _EVENT_TO_CHANNEL = {
            "threat_detected": "threat.new",
            "threat_resolved": "threat.resolved",
            "device_discovered": "device.new",
            "new_device": "device.new",
            "device_departed": "device.departed",
            "device_update": "device.update",
            "scan_complete": "scan.complete",
            "status_change": "status.update",
        }

        async def handler(event: Any) -> None:
            raw_type = event.event_type
            channel = _EVENT_TO_CHANNEL.get(raw_type, raw_type.replace("_", "."))
            timestamp = (
                event.timestamp.isoformat()
                if hasattr(event.timestamp, "isoformat")
                else str(event.timestamp)
            )
            await _ws_manager.broadcast(
                {"payload": event.payload, "timestamp": timestamp},
                channel=channel,
            )

        await self.bus.subscribe(
            [
                STREAM_EYES_THREATS,
                STREAM_EYES_DEVICE_UPDATES,
                STREAM_EYES_SCAN_RESULTS,
                STREAM_BRAIN_DECISIONS,
                STREAM_CORE_HEALTH,
            ],
            handler,
        )
